# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0484854a5f0ebb675a610278710b91afc64b01d0f31675e52e59c1dffc5bd43e663bdaf2318d74c790cddf71eec7e4d5056bee3b099c28b08a02ee0cd96a13cb

test:
  secret_key_base: e2222ed7da85a15a268223cede0e10d01d3ce067f79260e5c3da746b3392c64416ba6ce8ecf25ed6bfbb1b2a6b027c29d45bfbc7593053bef43d0cff9ddc187f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
